GET https://sls-notes-api.galhardoalex.com/v1/notes?limit=5&start=1712084724
# GET http://localhost:3000/prod/notes?limit=5&start=1712084724
content-type: application/json
app_user_id: galhardo_id
app_user_name: galhardo